spring:
  datasource:
     name: dev
     url: jdbc:mysql://localhost:3306/ashe
     username: root
     password: 2222

#reids
redis:
    host: 127.0.0.1
    port: 6379
    auth:
    max-idle: 5
    max-total: 10
    max-wait-millis: 3000